# Generated by Django 5.2.7 on 2025-11-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_is_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luckyfund',
            name='profile',
        ),
        migrations.AddField(
            model_name='luckyfund',
            name='number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
