# Generated by Django 5.2.7 on 2025-11-06 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_luckyfund_profile_luckyfund_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luckyfund',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack', to='base.luckypackage'),
        ),
    ]
