# Generated by Django 5.2.7 on 2025-11-15 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckyfund',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lucky_funding', to='base.profile'),
            preserve_default=False,
        ),
    ]
