# Generated by Django 5.2.7 on 2025-11-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_luckyfund_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckyfund',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_agent', to='base.profile'),
        ),
    ]
