# Generated by Django 5.2.9 on 2025-12-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_luckywinner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luckygift',
            name='amount',
        ),
        migrations.AddField(
            model_name='luckygift',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts_agent', to='base.profile'),
        ),
        migrations.AddField(
            model_name='luckygift',
            name='number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luckygift',
            name='profile',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='lucky_gifts', to='base.profile'),
            preserve_default=False,
        ),
    ]
