# Generated by Django 5.2.9 on 2025-12-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_fundsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='luckypackage',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
