# Generated by Django 5.2.9 on 2026-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_luckypackage_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='shops/profile_pics/')),
                ('shop_photo', models.ImageField(blank=True, null=True, upload_to='shops/photos/')),
                ('country', models.CharField(choices=[('BD', 'Bangladesh')], default='BD', max_length=5)),
                ('district', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chattogram', 'Chattogram'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Sylhet', 'Sylhet'), ('Barishal', 'Barishal'), ('Rangpur', 'Rangpur')], max_length=50)),
                ('location', models.CharField(help_text='Shop address / area', max_length=255)),
                ('google_map_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
