# Generated by Django 5.2.7 on 2026-02-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='theshop', to='base.shop'),
            preserve_default=False,
        ),
    ]
