# Generated by Django 5.2.7 on 2026-02-01 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
