# Generated by Django 5.2.7 on 2026-02-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_affiliate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
