# Generated by Django 4.2.28 on 2026-03-04 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_order_refer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=30)),
                ('rating', models.FloatField(default=5.0)),
                ('is_online', models.BooleanField(default=False)),
                ('lat', models.FloatField(default=23.7808)),
                ('lng', models.FloatField(default=90.4093)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(default='Rider', max_length=100)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('pickup_name', models.CharField(max_length=200)),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('dropoff_name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Moto'), ('car', 'Car'), ('cng', 'CNG')], default='car', max_length=10)),
                ('fare', models.IntegerField(default=0)),
                ('distance_km', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='base.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='base.driver')),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.ride')),
            ],
        ),
    ]
