# Generated by Django 6.0.4 on 2026-04-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_vr',
            field=models.BooleanField(default=False),
        ),
    ]
